'use client';

import TransitionLink from '@/components/TransitionLink';
import { useLanguage } from '@/components/LanguageProvider';
import { GITHUB_URL } from '@/components/SiteChrome';
import Icon, { type IconName } from '@/components/Icon';

// Edit this list to present the team.
const TEAM = [{ name: '@tairidrisov33-cmd', role: ['Founder · product & development', 'Основатель · продукт и разработка'], url: 'https://github.com/tairidrisov33-cmd' }];

export default function AboutContent({ professionCount, taskCount }: { professionCount: number; taskCount: number }) {
  const { language } = useLanguage();
  const ru = language === 'ru';
  const lang = ru ? 1 : 0;
  const sections: { icon: IconName; title: string; body: React.ReactNode }[] = ru ? [
    { icon: 'target', title: 'Проблема', body: <><p>Школьники выбирают специальность по описаниям, советам и рейтингам — почти никто не успевает попробовать саму работу. В итоге часть студентов понимает, что профессия «не их», только на втором-третьем курсе, потеряв время и деньги.</p><p>Стажировки и профпробы редки, а тесты на «тип личности» не показывают, как выглядит обычный рабочий день.</p></> },
    { icon: 'puzzle', title: 'Как работает PathTry', body: <ol><li><strong>Выбираешь профессию</strong> — {professionCount} направлений в 4 сферах.</li><li><strong>Проходишь 10 рабочих задач</strong> за ~10 минут: 7 решений с 5 вариантами и 3 письменных ответа. После каждого ответа — взгляд профессионала.</li><li><strong>Отмечаешь, заряжает ли задача</strong> — шкала интереса показывает не только «правильно», но и «моё ли это».</li><li><strong>Получаешь результат</strong>: совпадение с профессией, сильные стороны, предметы, вузы и следующие шаги.</li></ol> },
    { icon: 'book', title: 'Откуда задачи', body: <><p>Всего {taskCount} задач. Каждая основана на реальных рабочих действиях из базы профессий <a href="https://www.onetonline.org/" target="_blank" rel="noreferrer">O*NET OnLine</a> (Министерство труда США) и европейской таксономии навыков <a href="https://esco.ec.europa.eu/" target="_blank" rel="noreferrer">ESCO</a>. Мы переписали их в короткие сценарии простым языком для школьников и студентов.</p><p>Это инструмент для исследования, а не психологическая диагностика и не прогноз успеха.</p></> },
    { icon: 'compassNav', title: 'Как работает PathFinder AI', body: <><p>PathFinder — AI-наставник. Он разбирает письменные ответы по критериям задания (сильно / частично / не по заданию), даёт подсказки, не раскрывая ответ, и отвечает на вопросы о профессиях с учётом текущего задания.</p><p>Работает на модели Claude Haiku 4.5 (Anthropic) через серверный API — ключ хранится только на сервере. Если AI недоступен, PathFinder переключается на проверку по критериям и данным каталога, поэтому сайт работает всегда.</p><p>Ограничения безопасности: не больше 1000 символов в сообщении, 20 запросов в минуту, отказ от вредных и посторонних тем, никаких медицинских и юридических советов под видом настоящих.</p></> },
    { icon: 'shield', title: 'Приватность', body: <ul><li>Без регистрации и аккаунтов.</li><li>Прогресс и результаты хранятся только в твоём браузере (localStorage).</li><li>Письменные ответы и сообщения PathFinder отправляются на сервер (и AI-модели, если она подключена) только для ответа и не сохраняются в PathTry.</li><li>Контакт (email или Telegram) мы получаем, только если ты сам(а) запросишь дорожную карту.</li><li>Статистика посещений — анонимная (Vercel Analytics, без cookie).</li></ul> }
  ] : [
    { icon: 'target', title: 'The problem', body: <><p>Students choose a major from descriptions, advice, and rankings — almost nobody gets to try the actual work first. Many only realise a career is not for them in their second or third year, after losing time and money.</p><p>Internships and job shadowing are rare, and personality quizzes do not show what a normal working day looks like.</p></> },
    { icon: 'puzzle', title: 'How PathTry works', body: <ol><li><strong>Pick a profession</strong> — {professionCount} paths in 4 fields.</li><li><strong>Work through 10 tasks</strong> in about 10 minutes: 7 decisions with 5 options and 3 written answers, each followed by a pro insight.</li><li><strong>Rate how each task felt</strong> — the interest meter shows not only “right” but “is this me”.</li><li><strong>Get your result</strong>: match score, strengths, subjects, universities, and next steps.</li></ol> },
    { icon: 'book', title: 'Where tasks come from', body: <><p>All {taskCount} tasks are based on real work activities from the <a href="https://www.onetonline.org/" target="_blank" rel="noreferrer">O*NET OnLine</a> occupational database (US Department of Labor) and the European <a href="https://esco.ec.europa.eu/" target="_blank" rel="noreferrer">ESCO</a> skills taxonomy, rewritten as short, plain-language scenarios for students.</p><p>It is an exploration tool, not a psychological test or a prediction of success.</p></> },
    { icon: 'compassNav', title: 'How PathFinder AI works', body: <><p>PathFinder is the AI mentor. It reviews written answers against each task’s criteria (strong / partial / off the task), gives hints without revealing answers, and answers career questions with the current task in context.</p><p>It runs on Claude Haiku 4.5 (Anthropic) through a server-side API — the key never reaches the browser. If the AI is unavailable, PathFinder falls back to criteria-based review and catalog knowledge, so the site always works.</p><p>Safety limits: 1,000 characters per message, 20 requests per minute, refusal of harmful or off-topic requests, and no medical or legal advice presented as real advice.</p></> },
    { icon: 'shield', title: 'Privacy', body: <ul><li>No sign-up and no accounts.</li><li>Progress and results stay in your browser (localStorage).</li><li>Written answers and PathFinder messages go to the server (and to the AI model, when enabled) only to generate a reply, and PathTry does not store them.</li><li>We only receive a contact (email or Telegram) if you ask for a roadmap.</li><li>Visit statistics are anonymous (Vercel Analytics, cookieless).</li></ul> }
  ];
  return <main className="about-shell">
    <TransitionLink className="back" href="/"><Icon name="arrowLeft" size={15} />{ru ? 'На главную' : 'Home'}</TransitionLink>
    <div className="about-hero"><div className="kicker" style={{ marginTop: 40 }}>{ru ? 'О проекте' : 'About'}</div><h1>{ru ? 'Попробуй профессию, прежде чем выбрать её' : 'Try a profession before you choose it'}</h1><p>{ru ? 'PathTry — сервис микро-профориентации: 10 минут реальных рабочих задач вместо догадок о будущей профессии.' : 'PathTry is micro career exploration: ten minutes of real work tasks instead of guessing about your future job.'}</p></div>
    {sections.map((section) => <section className="about-section" key={section.title}><h2><span className="section-icon"><Icon name={section.icon} size={18} /></span>{section.title}</h2><div>{section.body}</div></section>)}
    <section className="about-section"><h2><span className="section-icon"><Icon name="users" size={18} /></span>{ru ? 'Команда' : 'Team'}</h2><div className="about-team">{TEAM.map((member) => <a href={member.url} target="_blank" rel="noreferrer" key={member.name}><strong>{member.name}</strong><span>{member.role[lang]}</span></a>)}</div></section>
    <div className="about-cta"><TransitionLink className="btn btn-primary" href="/#professions">{ru ? 'Попробовать профессию' : 'Try a profession'}<Icon name="arrowRight" size={16} /></TransitionLink><a className="btn btn-outline" href={GITHUB_URL} target="_blank" rel="noreferrer"><Icon name="code" size={16} />GitHub</a></div>
  </main>;
}
