import Link from 'next/link';
import { professions } from '@/data/professions';
import TransitionLink from '@/components/TransitionLink';
import ProfessionExplorer from '@/components/ProfessionExplorer';

export default function Home() {
  return <main>
    <section className="hero"><div><div className="kicker">Career reality check · 10 minutes</div><h1>Try a profession before you choose it.</h1><p>Five small tasks. A little honest reflection. A clearer feeling for what the work is really like before you commit to a major.</p><Link className="btn btn-primary" href="#professions">Explore professions <span>↓</span></Link></div><div className="hero-art"><TransitionLink className="hero-card featured-card" href={`/try/${professions[0].slug}`}><span className="featured-badge">Featured experiment</span><small>Today’s experiment</small><strong>Could this be your Tuesday?</strong><span className="muted">{professions[0].title} · 5 tasks</span><span className="featured-arrow">Try it ↗</span></TransitionLink><div className="orbit" /></div></section>
    <section className="section"><div className="section-head"><div><div className="kicker">No pressure, just perspective</div><h2>How it works</h2></div><span className="muted">Built for curious students</span></div><div className="steps"><div className="step"><span className="step-num">01</span><h3>Pick a path</h3><p>Choose a profession you are curious about, not one you have already decided on.</p></div><div className="step"><span className="step-num">02</span><h3>Try the real work</h3><p>Move through five tiny tasks based on the questions and choices professionals make every day.</p></div><div className="step"><span className="step-num">03</span><h3>Notice your reaction</h3><p>Get a thoughtful snapshot of your fit, your energy, and what to explore next.</p></div></div></section>
    <section className="section" id="professions"><div className="section-head"><div><div className="kicker">Choose your experiment</div><h2>Ten paths to try</h2></div><span className="muted">10 professions · 50 tasks</span></div><ProfessionExplorer professions={professions} /></section>
    <section className="method-section"><div><div className="kicker">Why these questions?</div><h2>Grounded in how work is actually described.</h2></div><div><p>PathTry turns common work activities into short, low-stakes scenarios. The starting point is the O*NET OnLine occupational database and the European ESCO skills taxonomy, then each task is rewritten for students in plain English.</p><p className="method-note">This is an exploration tool, not a psychological test or a prediction of future success.</p><div className="source-links"><a href="https://www.onetonline.org/" target="_blank" rel="noreferrer">O*NET OnLine ↗</a><a href="https://esco.ec.europa.eu/" target="_blank" rel="noreferrer">European ESCO ↗</a></div></div></section>
  </main>;
}
