'use client';

import { useEffect, useState } from 'react';
import type { Profession } from '@/data/professions';

export default function TaskRunner({ profession }: { profession: Profession }) {
  const [step, setStep] = useState(0); const [choice, setChoice] = useState<number | null>(null); const [text, setText] = useState(''); const [enjoyment, setEnjoyment] = useState<string | null>(null); const [answers, setAnswers] = useState<{ score: number; enjoyment: string; text: string }[]>([]);
  const task = profession.tasks[step]; const answered = task.type === 'choice' ? choice !== null : text.trim().length > 0; const choiceAnswered = choice !== null;
  useEffect(() => { const saved = localStorage.getItem(`pathtry-${profession.slug}`); if (saved) { try { const data = JSON.parse(saved); if (data.step !== undefined) { setStep(data.step); setAnswers(data.answers || []); } } catch {} } }, [profession.slug]);
  const selectChoice = (index: number) => { if (!choiceAnswered) setChoice(index); };
  const next = async () => { if (!answered || !enjoyment) return; let score = task.type === 'choice' ? (choice === task.answer ? 1 : 0) : (text.trim().length >= 20 ? 1 : 0); if (task.type === 'text') { try { const response = await fetch('/api/review', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ answer: text, profession: profession.title }) }); const review = await response.json(); if (typeof review.score === 'number') score = review.score; } catch { /* fallback score keeps the experience available */ } } const nextAnswers = [...answers, { score, enjoyment, text }]; if (step === profession.tasks.length - 1) { localStorage.setItem(`pathtry-${profession.slug}`, JSON.stringify({ step: 0, answers: nextAnswers })); window.location.href = `/result/${profession.slug}`; return; } const nextStep = step + 1; setAnswers(nextAnswers); setStep(nextStep); setChoice(null); setText(''); setEnjoyment(null); localStorage.setItem(`pathtry-${profession.slug}`, JSON.stringify({ step: nextStep, answers: nextAnswers })); };
  return <div><div className="task-meta"><span>Task {step + 1} of {profession.tasks.length}</span><span>{Math.round(((step) / profession.tasks.length) * 100)}% complete</span></div><div className="progress-track"><div className="progress-fill" style={{ width: `${((step) / profession.tasks.length) * 100}%` }} /></div><div className="task-box"><h2>{task.prompt}</h2>{task.context && <p className="context">{task.context}</p>}{task.type === 'choice' ? <div>{task.options?.map((option, index) => <button className={`option ${choice === index ? 'selected' : ''} ${choiceAnswered && index === task.answer ? 'correct' : ''} ${choice === index && choice !== task.answer ? 'wrong' : ''}`} onClick={() => selectChoice(index)} key={option}>{option}</button>)}{choiceAnswered && <div className="feedback">{choice === task.answer ? 'That is the strongest move. ' : 'Not quite, but this is useful information. '}{task.explanation}</div>}</div> : <textarea className="text-answer" value={text} onChange={(event) => setText(event.target.value)} placeholder={task.placeholder} />}{answered && <div className="enjoy"><p>Did you enjoy this?</p><div className="enjoy-options">{['Yes', 'So-so', 'No'].map((value) => <button className={enjoyment === value ? 'selected' : ''} onClick={() => setEnjoyment(value)} key={value}>{value}</button>)}</div></div>}<div className="task-actions"><button className="btn btn-primary" onClick={next} disabled={!answered || !enjoyment}>{step === profession.tasks.length - 1 ? 'See my result →' : 'Next task →'}</button></div></div></div>;
}
